#! /bin/sh -x
if xrandr -q | grep -w connected | grep DP1; then
	SINGLE_DISPLAY="false"
else
	SINGLE_DISPLAY="true"
fi

bspc monitor LVDS1 -d 1 2 3 4 5 6

# Setup for dual monitors
if ! $SINGLE_DISPLAY; then
	~/.config/bspwm/hotplug_monitor.sh
fi

bspc config remove_disabled_monitor true
bspc config remove_unplugged_monitor true
bspc config merge_overlapping_monitors [false, true]

sxhkd &

bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

feh --bg-fill $HOME/Images/backgrounds/default.jpg
$HOME/.config/polybar/launch.sh
/usr/bin/blueman-tray &
wmname LG3D
